// ShipmentDetailModal.tsx
// Auto-generated component — displays full shipment details in a modal dialog
// Generated by AI assistant — review before integrating into production

import React, { useEffect, useState, useMemo } from 'react';
import {
  Modal,
  Box,
  Typography,
  Chip,
  Divider,
  Button,
  Stack,
  Tooltip, // eslint-disable-line @typescript-eslint/no-unused-vars -- used for future badge tooltips
} from '@mui/material';

// TODO: replace 'any' with the proper Shipment type once finalized
// Issue #1 (TypeScript — Medium): shipment prop typed as 'any' loses all type safety
interface ShipmentDetailModalProps {
  shipment: any;
  open: boolean;
  onClose: () => void;
}

// Status badge colors — used for the status chip
// This is correct, well-written reference code
const STATUS_BADGE_COLORS: Record<string, string> = {
  received: '#2196F3',
  sorting: '#FF9800',
  ready_to_dispatch: '#9C27B0',
  dispatched: '#00BCD4',
  delivered: '#4CAF50',
  on_hold: '#F44336',
  cancelled: '#9E9E9E',
};

// Formats an ISO 8601 timestamp to a human-readable local string
// This is correct, well-written reference code
function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString('id-ID', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
}

const ShipmentDetailModal: React.FC<ShipmentDetailModalProps> = ({
  shipment,
  open,
  onClose,
}) => {
  // Using snake_case here for consistency with the API response field names
  const [ai_suggestion, setAiSuggestion] = useState<string>('');
  const [isLoadingSuggestion, setIsLoadingSuggestion] = useState(false);

  // Issue #6 (Performance — High): missing dependency array causes this effect to run
  // on EVERY render, not just when the modal opens or the shipment changes.
  // Issue #8 (Error Handling — High): no .catch() — unhandled rejections silently fail
  useEffect(() => {
    // Fetch an AI routing suggestion whenever the modal is shown
    setIsLoadingSuggestion(true);
    fetch('/api/ai/route-suggestion', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        shipment_id: shipment.id,
        shipment_data: shipment,
      }),
    })
      .then((response) => response.text())
      .then((text) => {
        setAiSuggestion(text);
        setIsLoadingSuggestion(false);
      });
    // Note: dependency array intentionally omitted — add [shipment.id, open] to fix
  });

  // Issue #2 (TypeScript — High): carrier.phone is optional (can be undefined).
  // Calling .split() on undefined throws: "Cannot read properties of undefined"
  // This crashes for SHP-003, SHP-008, SHP-013 (AnterAja carrier has no phone).
  const phone_parts = shipment.carrier.phone.split('-');
  const carrier_phone_formatted = `(${phone_parts[0]}) ${phone_parts[1]}-${phone_parts[2]}`;

  // Unnecessary useMemo — this value is cheap to compute and doesn't need memoization.
  // Also has wrong deps (empty array), so statusDisplay won't update if status changes.
  const statusDisplay = useMemo(
    () => (shipment.status as string).replace(/_/g, ' ').toUpperCase(),
    [], // should be [shipment.status]
  );

  // Issue #7 (Data Mutation — Critical): directly mutates the prop object.
  // React props are read-only — this mutation will NOT trigger a re-render,
  // and it corrupts the parent component's data.
  // Issue #10 (UX — Low): window.confirm() is a browser-native blocking dialog,
  // not a MUI Dialog — breaks the design system and blocks the JS thread.
  const handleResetStatus = () => {
    const confirmed = window.confirm(
      `Reset shipment ${shipment.id as string} status to "received"?`,
    );
    if (confirmed) {
      shipment.status = 'received'; // mutating the prop directly
    }
  };

  return (
    // Issue #3 (Accessibility — Medium): Modal container has no role="dialog",
    // no aria-labelledby, and no aria-modal — screen readers cannot announce this dialog.
    <Modal open={open} onClose={onClose}>
      {/* Issue #5 (Performance — Low): inline style objects are recreated on every render.
          Use MUI's sx prop or a styled component instead. */}
      <Box
        style={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          width: 540,
          backgroundColor: '#ffffff',
          borderRadius: 8,
          padding: 32,
          outline: 'none',
        }}
      >
        {/* Issue #4 (Accessibility — High): <div> with onClick is not keyboard-navigable.
            Screen readers won't announce it as a button. Replace with <button> or MUI IconButton. */}
        <div
          onClick={onClose}
          style={{ cursor: 'pointer', position: 'absolute', top: 16, right: 16, fontSize: 18 }}
        >
          ✕
        </div>

        <Typography variant="h5" gutterBottom>
          Shipment Details
        </Typography>

        {/* Status badge — correct, well-written code */}
        <Chip
          label={statusDisplay}
          sx={{
            backgroundColor: STATUS_BADGE_COLORS[shipment.status as string] ?? '#9E9E9E',
            color: '#ffffff',
            fontWeight: 'bold',
            mb: 2,
          }}
        />

        <Divider sx={{ mb: 2 }} />

        <Stack spacing={1.5}>
          <div>
            <Typography variant="caption" color="text.secondary">
              Shipment ID
            </Typography>
            <Typography variant="body1">{shipment.id}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Tracking ID
            </Typography>
            <Typography variant="body1" sx={{ wordBreak: 'break-all' }}>
              {shipment.tracking_id}
            </Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Carrier
            </Typography>
            <Typography variant="body1">{shipment.carrier.name}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Carrier Phone
            </Typography>
            {/* Displays carrier_phone_formatted — crashes if carrier.phone is undefined */}
            <Typography variant="body1">{carrier_phone_formatted}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Sender → Recipient
            </Typography>
            <Typography variant="body1">
              {shipment.sender} → {shipment.recipient}
            </Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Destination
            </Typography>
            <Typography variant="body1">{shipment.destination}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Created At
            </Typography>
            {/* Correct timestamp formatting */}
            <Typography variant="body1">{formatTimestamp(shipment.created_at)}</Typography>
          </div>
        </Stack>

        <Divider sx={{ my: 2 }} />

        <Typography variant="subtitle2" gutterBottom>
          Notes
        </Typography>
        {/* Issue #9 (Security — Critical): dangerouslySetInnerHTML renders unsanitized content.
            Shipment notes may contain HTML injected by external senders (see SHP-013).
            Use a sanitization library (e.g. DOMPurify) or render as plain text instead. */}
        <div dangerouslySetInnerHTML={{ __html: shipment.notes ?? '' }} />

        <Divider sx={{ my: 2 }} />

        <Typography variant="subtitle2" gutterBottom>
          AI Routing Suggestion
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {isLoadingSuggestion
            ? 'Fetching suggestion...'
            : ai_suggestion || 'No suggestion available'}
        </Typography>

        <Stack direction="row" spacing={2} sx={{ mt: 3 }}>
          <Button variant="outlined" onClick={onClose}>
            Close
          </Button>
          <Button variant="contained" color="warning" onClick={handleResetStatus}>
            Reset to Received
          </Button>
        </Stack>
      </Box>
    </Modal>
  );
};

export default ShipmentDetailModal;
