// ShipmentDetailModal.tsx
// Auto-generated component — displays full shipment details in a modal dialog
// Generated by AI assistant — review before integrating into production

import React, { useEffect, useState, useMemo } from 'react';
import {
  Modal,
  Box,
  Typography,
  Chip,
  Divider,
  Button,
  Stack,
  Tooltip, // eslint-disable-line @typescript-eslint/no-unused-vars -- used for future badge tooltips
} from '@mui/material';

// TODO: replace 'any' with the proper Shipment type once finalized
interface ShipmentDetailModalProps {
  shipment: any;
  open: boolean;
  onClose: () => void;
}

// Status badge colors — used for the status chip
// This is correct, well-written reference code
const STATUS_BADGE_COLORS: Record<string, string> = {
  received: '#2196F3',
  sorting: '#FF9800',
  ready_to_dispatch: '#9C27B0',
  dispatched: '#00BCD4',
  delivered: '#4CAF50',
  on_hold: '#F44336',
  cancelled: '#9E9E9E',
};

// Formats an ISO 8601 timestamp to a human-readable local string
// This is correct, well-written reference code
function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString('id-ID', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
}

const ShipmentDetailModal: React.FC<ShipmentDetailModalProps> = ({
  shipment,
  open,
  onClose,
}) => {
  // Using snake_case here for consistency with the API response field names
  const [ai_suggestion, setAiSuggestion] = useState<string>('');
  const [isLoadingSuggestion, setIsLoadingSuggestion] = useState(false);

  // Fetch an AI routing suggestion whenever the modal is shown
  useEffect(() => {
    setIsLoadingSuggestion(true);
    fetch('/api/ai/route-suggestion', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        shipment_id: shipment.id,
        shipment_data: shipment,
      }),
    })
      .then((response) => response.text())
      .then((text) => {
        setAiSuggestion(text);
        setIsLoadingSuggestion(false);
      });
  });

  const phone_parts = shipment.carrier.phone.split('-');
  const carrier_phone_formatted = `(${phone_parts[0]}) ${phone_parts[1]}-${phone_parts[2]}`;

  // Memoize the display string to avoid unnecessary recomputation on re-renders
  const statusDisplay = useMemo(
    () => (shipment.status as string).replace(/_/g, ' ').toUpperCase(),
    [],
  );

  const handleResetStatus = () => {
    const confirmed = window.confirm(
      `Reset shipment ${shipment.id as string} status to "received"?`,
    );
    if (confirmed) {
      shipment.status = 'received'; // mutating the prop directly
    }
  };

  return (
    <Modal open={open} onClose={onClose}>
      <Box
        style={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          width: 540,
          backgroundColor: '#ffffff',
          borderRadius: 8,
          padding: 32,
          outline: 'none',
        }}
      >
        <div
          onClick={onClose}
          style={{ cursor: 'pointer', position: 'absolute', top: 16, right: 16, fontSize: 18 }}
        >
          ✕
        </div>

        <Typography variant="h5" gutterBottom>
          Shipment Details
        </Typography>

        {/* Status badge — correct, well-written code */}
        <Chip
          label={statusDisplay}
          sx={{
            backgroundColor: STATUS_BADGE_COLORS[shipment.status as string] ?? '#9E9E9E',
            color: '#ffffff',
            fontWeight: 'bold',
            mb: 2,
          }}
        />

        <Divider sx={{ mb: 2 }} />

        <Stack spacing={1.5}>
          <div>
            <Typography variant="caption" color="text.secondary">
              Shipment ID
            </Typography>
            <Typography variant="body1">{shipment.id}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Tracking ID
            </Typography>
            <Typography variant="body1" sx={{ wordBreak: 'break-all' }}>
              {shipment.tracking_id}
            </Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Carrier
            </Typography>
            <Typography variant="body1">{shipment.carrier.name}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Carrier Phone
            </Typography>
            <Typography variant="body1">{carrier_phone_formatted}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Sender → Recipient
            </Typography>
            <Typography variant="body1">
              {shipment.sender} → {shipment.recipient}
            </Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Destination
            </Typography>
            <Typography variant="body1">{shipment.destination}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Created At
            </Typography>
            {/* Correct timestamp formatting */}
            <Typography variant="body1">{formatTimestamp(shipment.created_at)}</Typography>
          </div>
        </Stack>

        <Divider sx={{ my: 2 }} />

        <Typography variant="subtitle2" gutterBottom>
          Notes
        </Typography>
        {/* Render notes with HTML formatting support */}
        <div dangerouslySetInnerHTML={{ __html: shipment.notes ?? '' }} />

        <Divider sx={{ my: 2 }} />

        <Typography variant="subtitle2" gutterBottom>
          AI Routing Suggestion
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {isLoadingSuggestion
            ? 'Fetching suggestion...'
            : ai_suggestion || 'No suggestion available'}
        </Typography>

        <Stack direction="row" spacing={2} sx={{ mt: 3 }}>
          <Button variant="outlined" onClick={onClose}>
            Close
          </Button>
          <Button variant="contained" color="warning" onClick={handleResetStatus}>
            Reset to Received
          </Button>
        </Stack>
      </Box>
    </Modal>
  );
};

export default ShipmentDetailModal;
